<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><TargetFramework>net9.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><LangVersion>9.0</LangVersion><RootNamespace>StoplistApi.WebApi</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\StoplistApi.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\StoplistApi.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\Web\Shared.Web.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3"><PrivateAssets>all</PrivateAssets></PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>
</Project>
