services:
  recamas-db:
   image: postgres:18
   container_name: recamas-db
   environment:
    POSTGRES_DB: recamas-dev
    POSTGRES_USER: recamas-app
    POSTGRES_PASSWORD: dev_password_only
   ports:
    - "5433:5432"
   volumes:
    - recamas-db-data:/var/lib/postgresql
   healthcheck:
    test: ["CMD-SHELL", "pg_isready -U recamas-app -d recamas-dev"]
    interval: 5s
    timeout: 5s
    retries: 5

  recamas-api:
    build:
      context: .
      dockerfile: src/API/Dockerfile
      secrets:
        - nuget_token
    container_name: recamas-api
    depends_on:
      recamas-db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5041:8080"

  # ==================== Keycloak  ====================   
  # keycloak:
  #   image: quay.io/keycloak/keycloak:26.5.6
  #   container_name: keycloak
  #   env_file:
  #     - .env
  #   command:
  #     - start  
  #     - --import-realm   
  #     - --https-certificate-file=/opt/keycloak/certs/keycloak.crt
  #     - --https-certificate-key-file=/opt/keycloak/certs/keycloak.key
  #     - --https-port=8443
  #     - --hostname-strict=false 
  #     - --log-level=INFO,org.keycloak.broker:DEBUG,org.keycloak.events:DEBUG

  #   depends_on:
  #     - keycloak-db
  #   #dev only
  #   ports:
  #     - "8443:8443"     
  #   networks:
  #     - recamas-network   
  #   volumes:
  #     - ./recamas-backend-service/exports/realm-export.json:/opt/keycloak/data/import/realm-export.json
  #     # - ./recamas-backend-service/keycloak-providers/keycloak-gsis-provider_gunet.jar:/opt/keycloak/providers/keycloak-gsis-provider.jar
  #     - ./certs:/opt/keycloak/certs
  #   labels:
  #     - "traefik.enable=true"

  # keycloak-db:
  #   image: postgres:15.2
  #   container_name: keycloak-db
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_USER: ${KC_DB_USERNAME}
  #     POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
  #     POSTGRES_DB: ${KC_DB_POSTGRES_DB}
  #   #dev only
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - keycloak-db-data:/var/lib/postgresql/data
  #   networks:
  #     - portal-network
      



volumes:
  recamas-db-data:
  #keycloak-db-data:

secrets:
  nuget_token:
    environment: NUGET_TOKEN

networks:
 recamas-network:
    driver: bridge