<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net9.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><LangVersion>9.0</LangVersion></PropertyGroup>
  <ItemGroup><ProjectReference Include="..\Domain\CassApi.Domain.csproj" /></ItemGroup>
</Project>
