server {
    listen 8080;
    resolver 127.0.0.11 valid=10s ipv6=off;

    location = /health {
        access_log off;
        return 200 'healthy';
        add_header Content-Type text/plain;
    }

    location /police/police-checks/v1/stoplist/ {
        set $stoplist_upstream http://stoplist-api:8080;
        proxy_pass $stoplist_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /police/police-checks/v1/arrivals-departures/ {
        set $arrivals_upstream http://arrivals-api:8080;
        proxy_pass $arrivals_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
