import type { RecamasCase } from './Details/casesTypes';
import { AvrCaseStage, CaseFlag, CaseStatus, CaseType } from './Details/casesTypes';

export const casesMock: readonly RecamasCase[] = [
  {
    caseId: 'CAS-10118',
    tcnName: 'Ahmad Hassan',
    arc: '10024581',
    type: CaseType.Avr,
    currentStage: AvrCaseStage.ReturnImplementation,
    currentStatus: CaseStatus.InProgress,
    needsAttention: false,
    caseFlags: [],
    createdDate: '2026-08-14',
    assignedOfficer: 'Maria Ioannou',
  },
  {
    caseId: 'CAS-10872',
    tcnName: 'Fatima Rahimi',
    arc: '10031844',
    type: CaseType.VoluntaryReturnByOwnMeans,
    currentStage: AvrCaseStage.Closed,
    currentStatus: CaseStatus.Completed,
    needsAttention: false,
    caseFlags: [],
    createdDate: '2026-07-02',
    assignedOfficer: 'Maria Ioannou',
  },
  {
    caseId: 'CAS-10041',
    tcnName: 'Chinedu Okafor',
    arc: '10040217',
    type: CaseType.ForcedReturn,
    currentStage: AvrCaseStage.Counselling,
    currentStatus: CaseStatus.Pending,
    needsAttention: true,
    caseFlags: [CaseFlag.NeedsAttention, CaseFlag.NoTravelDocument],
    createdDate: '2026-09-01',
    assignedOfficer: null,
  },
  {
    caseId: 'CAS-10603',
    tcnName: 'Aisha Khan',
    arc: '10046790',
    type: CaseType.Avr,
    currentStage: AvrCaseStage.ApplicationProcessing,
    currentStatus: CaseStatus.InProgress,
    needsAttention: false,
    caseFlags: [CaseFlag.Minor],
    createdDate: '2026-06-21',
    assignedOfficer: 'Petros Georgiou',
  },
  {
    caseId: 'CAS-11440',
    tcnName: 'Olena Bondarenko',
    arc: '10051102',
    type: CaseType.VoluntaryReturnByOwnMeans,
    currentStage: AvrCaseStage.Reintegration,
    currentStatus: CaseStatus.InProgress,
    needsAttention: false,
    caseFlags: [],
    createdDate: '2026-03-18',
    assignedOfficer: 'Petros Georgiou',
  },
  {
    caseId: 'CAS-10915',
    tcnName: 'Mohamed Farah',
    arc: '10058863',
    type: CaseType.ForcedReturn,
    currentStage: AvrCaseStage.PreReturn,
    currentStatus: CaseStatus.Cancelled,
    needsAttention: true,
    caseFlags: [CaseFlag.NeedsAttention, CaseFlag.NoArc],
    createdDate: '2026-05-09',
    assignedOfficer: null,
  },
  {
    caseId: 'CAS-10277',
    tcnName: 'Nour El-Sayed',
    arc: '10064128',
    type: CaseType.Avr,
    currentStage: AvrCaseStage.Evaluation,
    currentStatus: CaseStatus.Pending,
    needsAttention: false,
    caseFlags: [],
    createdDate: '2026-09-10',
    assignedOfficer: 'Maria Ioannou',
  },
  {
    caseId: 'CAS-10329',
    tcnName: 'Yusuf Demir',
    arc: '10072211',
    type: CaseType.Avr,
    currentStage: AvrCaseStage.Counselling,
    currentStatus: CaseStatus.Pending,
    needsAttention: false,
    caseFlags: [CaseFlag.Minor],
    createdDate: '2026-04-05',
    assignedOfficer: 'Christina Papadaki',
  },
  {
    caseId: 'CAS-10456',
    tcnName: 'Amina Diallo',
    arc: '10078845',
    type: CaseType.ForcedReturn,
    currentStage: AvrCaseStage.ReturnImplementation,
    currentStatus: CaseStatus.InProgress,
    needsAttention: true,
    caseFlags: [CaseFlag.NeedsAttention],
    createdDate: '2026-02-22',
    assignedOfficer: 'Christina Papadaki',
  },
  {
    caseId: 'CAS-10561',
    tcnName: 'Rustam Nazarov',
    arc: '10083390',
    type: CaseType.VoluntaryReturnByOwnMeans,
    currentStage: AvrCaseStage.Closed,
    currentStatus: CaseStatus.Completed,
    needsAttention: false,
    caseFlags: [],
    createdDate: '2026-01-30',
    assignedOfficer: 'Petros Georgiou',
  },
  {
    caseId: 'CAS-10688',
    tcnName: 'Grace Adeyemi',
    arc: '10089902',
    type: CaseType.Avr,
    currentStage: AvrCaseStage.Evaluation,
    currentStatus: CaseStatus.InProgress,
    needsAttention: false,
    caseFlags: [CaseFlag.NoTravelDocument],
    createdDate: '2026-05-27',
    assignedOfficer: null,
  },
  {
    caseId: 'CAS-10734',
    tcnName: 'Karim Aziz',
    arc: '10091557',
    type: CaseType.ForcedReturn,
    currentStage: AvrCaseStage.PreReturn,
    currentStatus: CaseStatus.Pending,
    needsAttention: true,
    caseFlags: [CaseFlag.NeedsAttention, CaseFlag.NoArc],
    createdDate: '2026-08-01',
    assignedOfficer: 'Maria Ioannou',
  },
];
