using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using RECAMAS.Domain.Entities.TCNProfile;
using RECAMAS.Domain.Entities.Case;
using RECAMAS.Domain.Entities.Detention;
using RECAMAS.Domain.Entities.ReturnImplementation;
using RECAMAS.Domain.Entities.Admin;

namespace RECAMAS.Infrastructure.Database.Configurations;


public sealed class DetentionUpdateIssueConfiguration : IEntityTypeConfiguration<DetentionUpdateIssue>
{
    public void Configure(EntityTypeBuilder<DetentionUpdateIssue> builder)
    {
        builder.ToTable("detention_update_issues", schema: "detention");
        EntityConfiguration.ConfigureBase(builder);
        builder.Property(e => e.IssueId).HasComment("System-generated — string");
        builder.Property(e => e.UpdateIssueType).HasComment("Medical | YKERequest | TcnStatusUpdate | Other");
        builder.Property(e => e.IsAutoGenerated).HasComment("True αν από interface update");
        builder.HasIndex(e => e.IssueId).IsUnique();
    }
}
