// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RECAMAS.Infrastructure.Database;

#nullable disable

namespace RECAMAS.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260829174229_InitialTCNProfile")]
    partial class InitialTCNProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RECAMAS.Domain.Entities.TCNProfile.TCNIdentityDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AttachmentDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("text");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTravelDocument")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("IssuingAuthority")
                        .HasColumnType("text");

                    b.Property<string>("IssuingCountry")
                        .HasColumnType("text");

                    b.Property<Guid?>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<long>("TCNProfileId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber");

                    b.HasIndex("TCNProfileId");

                    b.ToTable("tcn_identity_documents", "tcn_profile");
                });

            modelBuilder.Entity("RECAMAS.Domain.Entities.TCNProfile.TCNNationality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("IdentificationStatus")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("NationalityCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long>("TCNProfileId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TCNProfileId");

                    b.ToTable("tcn_nationalities", "tcn_profile");
                });

            modelBuilder.Entity("RECAMAS.Domain.Entities.TCNProfile.TCNProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Arc")
                        .HasColumnType("text");

                    b.Property<string>("CassAddress")
                        .HasColumnType("text");

                    b.Property<string>("CassFileNo")
                        .HasColumnType("text");

                    b.Property<string>("CassPhone")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DisplayCode")
                        .HasColumnType("text");

                    b.Property<string>("EurodacNumber")
                        .HasColumnType("text");

                    b.Property<string>("FirstNameEl")
                        .HasColumnType("text");

                    b.Property<string>("FirstNameEn")
                        .HasColumnType("text");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastNameEl")
                        .HasColumnType("text");

                    b.Property<string>("LastNameEn")
                        .HasColumnType("text");

                    b.Property<string>("MdAddress")
                        .HasColumnType("text");

                    b.Property<string>("MdFileNo")
                        .HasColumnType("text");

                    b.Property<string>("MdPhone")
                        .HasColumnType("text");

                    b.Property<string>("MiddleNameEl")
                        .HasColumnType("text");

                    b.Property<string>("MiddleNameEn")
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("text");

                    b.Property<Guid?>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RelationshipToMdFile")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Arc");

                    b.HasIndex("DisplayCode")
                        .IsUnique()
                        .HasFilter("\"DisplayCode\" IS NOT NULL");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Arc", "FirstNameEn", "LastNameEn");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Arc", "FirstNameEn", "LastNameEn"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Arc", "FirstNameEn", "LastNameEn"), new[] { "gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops" });

                    b.ToTable("tcn_profiles", "tcn_profile");
                });

            modelBuilder.Entity("RECAMAS.Domain.Entities.TCNProfile.TCNIdentityDocument", b =>
                {
                    b.HasOne("RECAMAS.Domain.Entities.TCNProfile.TCNProfile", null)
                        .WithMany("IdentityDocuments")
                        .HasForeignKey("TCNProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RECAMAS.Domain.Entities.TCNProfile.TCNNationality", b =>
                {
                    b.HasOne("RECAMAS.Domain.Entities.TCNProfile.TCNProfile", null)
                        .WithMany("Nationalities")
                        .HasForeignKey("TCNProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RECAMAS.Domain.Entities.TCNProfile.TCNProfile", b =>
                {
                    b.Navigation("IdentityDocuments");

                    b.Navigation("Nationalities");
                });
#pragma warning restore 612, 618
        }
    }
}
