using RECAMAS.Domain.Common;
using RECAMAS.Domain.Enums;
using RECAMAS.Domain.Entities.TCNProfile;
using RECAMAS.Domain.Entities.Case;
using RECAMAS.Domain.Entities.Detention;
using RECAMAS.Domain.Entities.ReturnImplementation;
using RECAMAS.Domain.Entities.Admin;

namespace RECAMAS.Domain.Entities.Detention;

/// Ενημέρωση / πρόβλημα κατά κράτηση (§4.5.2.5.5)
public class DetentionUpdateIssue : BaseEntity
{
    public long ForcedReturnCaseId { get; set; }

    public string IssueId { get; set; } = null!;                 // System-generated — string
    public DetentionIssueType UpdateIssueType { get; set; } // Medical | YKERequest | TcnStatusUpdate | Other
    public DateTimeOffset IssueDateTime { get; set; }
    public string? Notes { get; set; }
    public bool RequiresReassessment { get; set; }
    public bool RequiresNewOrders { get; set; }
    public bool BlocksDeparture { get; set; }
    public string? AttachmentsPath { get; set; }
    public bool IsAutoGenerated { get; set; }           // True αν από interface update

    public ForcedReturnCase ForcedReturnCase { get; set; } = null!;
}
